--ACTUAL_TARGET VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_ACTUAL_TARGET
AS
SELECT B.STORENUMBER,
A.DIMCHANNELID,
A.DIMPRODUCTID,
A.SALEAMOUNT AS SalesActualAmount,
C.SALETARGETAMOUNT AS SalesTargetAmount,
A.DIMSALEDATEID AS DimDateID,
D.DATE AS FullDate
FROM FACT_SALESACTUAL A 
LEFT JOIN DIM_STORE B ON A.DIMSTOREID = B.DIMSTOREID
LEFT JOIN FACT_SRCSALESTARGET C ON A.DIMSTOREID = C.DIMSTOREID 
        AND A.DIMSALEDATEID = C.DIMTARGETDATEID
        AND A.DIMCHANNELID = C.DIMCHANNELID
LEFT JOIN DIM_DATE D ON A.DIMSALEDATEID = D.DATE_PKEY
WHERE B.STORENUMBER IN (5, 8)

--PRODUCT_SALES VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_PRODUCT_SALES
AS
SELECT B.STORENUMBER,
C.DIMPRODUCTID,
C.PRODUCTCATEGORY,
A.SALEAMOUNT,
A.SALEQUANTITY,
A.SALETOTALPROFIT,
A.DIMSALEDATEID AS DimDateID,
D.DATE AS FullDate
FROM FACT_SALESACTUAL A 
LEFT JOIN DIM_STORE B ON A.DIMSTOREID = B.DIMSTOREID
LEFT JOIN DIM_PRODUCT C ON A.DIMPRODUCTID = C.DIMPRODUCTID
LEFT JOIN DIM_DATE D ON A.DIMSALEDATEID = D.DATE_PKEY
WHERE B.STORENUMBER IN (5, 8)

--STORE_LOCATION VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_STORE_LOCATION
AS
SELECT B.STORENUMBER,
A.DIMCHANNELID, 
C.DIMPRODUCTID,
A.DIMLOCATIONID,
C.PRODUCTCATEGORY,
A.SALEAMOUNT,
A.SALEQUANTITY,
A.SALETOTALPROFIT,
E.STATE, 
A.DIMSALEDATEID AS DimDateID,
D.DATE AS FullDate
FROM FACT_SALESACTUAL A 
LEFT JOIN DIM_STORE B ON A.DIMSTOREID = B.DIMSTOREID
LEFT JOIN DIM_PRODUCT C ON A.DIMPRODUCTID = C.DIMPRODUCTID
LEFT JOIN DIM_DATE D ON A.DIMSALEDATEID = D.DATE_PKEY
LEFT JOIN DIM_LOCATION E ON B.DIMLOCATIONID = E.DIMLOCATIONID
WHERE B.STORENUMBER <> -1

--SALE_ACTUAL_TARGET VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_SALE_ACTUAL_TARGET
AS
SELECT DIMDATEID, 
    FULLDATE, 
    STORENUMBER, 
    DIMCHANNELID, 
    SalesTargetAmount, 
    SUM(SALESACTUALAMOUNT) AS TOTALSALE,
    ROUND(AVG(SALESACTUALAMOUNT), 2) AS AVGSALESTRANS 
FROM VIEW_ACTUAL_TARGET
GROUP BY DIMDATEID, FULLDATE, STORENUMBER, DIMCHANNELID, SalesTargetAmount

--PRODUCT_SOLD VIEW
CREATE OR REPLACE SECURE VIEW PUBLIC.VIEW_PRODUCT_SOLD
AS
select DIMDATEID
    FULLDATE, 
    STORENUMBER, 
    DIMPRODUCTID, 
    ROUND(AVG(SALEQUANTITY), 2) AS AVGUNITSOLD 
FROM VIEW_PRODUCT_SALES
GROUP BY DIMDATEID, FULLDATE, STORENUMBER, DIMPRODUCTID